# Generated by Django 3.2.3 on 2021-05-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
